name: Run NestJS Command

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 09 * * *'

jobs:
  run-command:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Run NestJS Command
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
          CALL_ME_BOT_API_KEY: ${{ secrets.CALL_ME_BOT_API_KEY }}
        run: npm run start:prod -- generate-ice-bath-message