name: Run NestJS Command

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Run NestJS Command
        run: npm run start:prod -- generate-ice-bath-message